# build step
FROM node:lts AS builder

WORKDIR /app

COPY . .

RUN npm install

# build step
FROM node:lts

RUN apt update && apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

COPY . .
COPY --from=builder /app/node_modules ./node_modules

ENV PATH=/app/node_modules/.bin:${PATH}

CMD [ "npm", "run", "dev" ]
